name: GoLangTest

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        working-directory: ./2025_CakeLand_API
        run: go mod tidy

      - name: Run tests
        working-directory: ./2025_CakeLand_API
        run: make tests